"use client";
import "./account.css";
import Link from "next/link";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowRight, Check, Home, KeyRound, ShieldCheck } from "lucide-react";

export default function AccountPage(){
  const [mode,setMode]=useState<"register"|"login">("register"); const [role,setRole]=useState("buyer"); const [error,setError]=useState(""); const [busy,setBusy]=useState(false); const router=useRouter();
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");const data=new FormData(event.currentTarget);const response=await fetch("/api/account",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:mode,name:data.get("name"),email:data.get("email"),password:data.get("password"),role})});const body=await response.json();if(!response.ok){setError(body.error);setBusy(false);return;}router.push("/portal");router.refresh();}
  return <main className="account-page"><section className="account-story"><Link href="/" className="account-brand"><span>L</span>listwise.</Link><div><p className="eyebrow">Your move, organised</p><h1>One place for every viewing, message and offer.</h1><ul><li><Check/>Reuse your buyer profile</li><li><Check/>Chat directly around each viewing</li><li><Check/>Keep seller bookings and offers together</li></ul></div><small>Your password is salted and hashed. Sessions are stored securely in Neon.</small></section><section className="account-panel"><div className="auth-switch"><button className={mode==="register"?"active":""} onClick={()=>setMode("register")}>Create account</button><button className={mode==="login"?"active":""} onClick={()=>setMode("login")}>Sign in</button></div><form onSubmit={submit}><div className="account-icon">{mode==="register"?<Home/>:<KeyRound/>}</div><h2>{mode==="register"?"Make Listwise yours":"Welcome back"}</h2><p>{mode==="register"?"Start with the side of the move you’re on today.":"Open your property workspace."}</p>{mode==="register"&&<><div className="role-switch"><button type="button" className={role==="buyer"?"active":""} onClick={()=>setRole("buyer")}>I’m buying</button><button type="button" className={role==="seller"?"active":""} onClick={()=>setRole("seller")}>I’m selling</button><button type="button" className={role==="both"?"active":""} onClick={()=>setRole("both")}>Both</button></div><label>Full name<input name="name" autoComplete="name" required/></label></>}<label>Email address<input name="email" type="email" autoComplete="email" required/></label><label>Password<input name="password" type="password" autoComplete={mode==="register"?"new-password":"current-password"} minLength={8} required/></label>{error&&<p className="auth-error">{error}</p>}<button className="account-submit" disabled={busy}>{busy?"Opening your workspace…":mode==="register"?"Create my account":"Sign in"}<ArrowRight/></button><div className="auth-security"><ShieldCheck/>Private account data is kept in the dedicated Listwise database.</div></form></section></main>;
}
