export type Listing = { slug:string; title:string; address:string; area:string; postcode:string; price:number; qualifier:string; bedrooms:number; bathrooms:number; type:"Apartment"|"Terrace"|"Semi-detached"|"Detached"; status:"For sale"|"New"|"Under offer"; image:string; collection:string[]; description:string; sourceUrl:string };
const photos=[
"https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1400&q=82",
"https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1400&q=82",
"https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1400&q=82",
"https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=1400&q=82",
"https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=1400&q=82",
"https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1400&q=82"];
export const listings:Listing[]=[
{slug:"fairfax-didsbury",title:"The Fairfax",address:"611a Wilmslow Road",area:"Didsbury",postcode:"M20",price:375000,qualifier:"Asking price",bedrooms:2,bathrooms:2,type:"Apartment",status:"For sale",image:photos[1],collection:["Village life","First-time favourites"],description:"A contemporary third-floor apartment with two double bedrooms, private balcony and secure gated parking, within walking distance of Didsbury and West Didsbury villages.",sourceUrl:"https://www.gascoignehalman.co.uk/property-details/1027000/greater-manchester/didsbury/611a-wilmslow-road"},
{slug:"fog-lane-didsbury",title:"Fog Lane",address:"Fog Lane",area:"Didsbury",postcode:"M20",price:495000,qualifier:"Asking price",bedrooms:3,bathrooms:1,type:"Semi-detached",status:"For sale",image:photos[3],collection:["Metrolink movers","Family space"],description:"A spacious bay-fronted home with two reception rooms, off-road parking and a rear garden, moments from Didsbury Village, Fog Lane Park and transport links.",sourceUrl:"https://www.gascoignehalman.co.uk/property-details/1044677/manchester/didsbury/fog-lane-1"},
{slug:"wilmslow-road-triplex",title:"Wilmslow Road",address:"Wilmslow Road",area:"Didsbury",postcode:"M20",price:395000,qualifier:"Asking price",bedrooms:4,bathrooms:3,type:"Apartment",status:"For sale",image:photos[0],collection:["Village life","Family space"],description:"A substantial triplex apartment in the heart of Didsbury Village, with private access, two reception rooms and four bedrooms across 1,410 sq ft.",sourceUrl:"https://www.gascoignehalman.co.uk/property-details/1038935/manchester/didsbury/wilmslow-road-1"},
{slug:"280-fog-lane",title:"280 Fog Lane",address:"Fog Lane",area:"Didsbury",postcode:"M20",price:190000,qualifier:"Asking price",bedrooms:2,bathrooms:2,type:"Apartment",status:"For sale",image:photos[5],collection:["Metrolink movers","First-time favourites"],description:"A light second-floor apartment with two double bedrooms, two bathrooms, open-plan living, allocated parking and no onward chain.",sourceUrl:"https://www.gascoignehalman.co.uk/property-details/1051714/manchester/didsbury/280-fog-lane"},
{slug:"park-lane-hale",title:"Park House",address:"15 Park Lane",area:"Hale",postcode:"WA15",price:3495000,qualifier:"Asking price",bedrooms:5,bathrooms:6,type:"Detached",status:"For sale",image:photos[4],collection:["Village life","Family space"],description:"A landmark gated home close to Hale Village, combining five bedrooms with a pool, gym, lift, large garden and double garage.",sourceUrl:"https://www.gascoignehalman.co.uk/property-details/839125a9-d6d9-46d8-bdd1-cb814ca03c52/greater-manchester/altrincham/park-lane-1"},
{slug:"richmond-road-altrincham",title:"Richmond Road",address:"Richmond Road",area:"Altrincham",postcode:"WA14",price:655000,qualifier:"Asking price",bedrooms:4,bathrooms:2,type:"Semi-detached",status:"New",image:photos[0],collection:["Metrolink movers","Family space"],description:"A characterful four-bedroom period home arranged over three floors, within reach of Altrincham centre, John Leigh Park and Trafford schools.",sourceUrl:"https://www.gascoignehalman.co.uk/property-details/1014344/greater-manchester/altrincham/richmond-road-1"},
{slug:"thorn-bank-lodge",title:"Thorn Bank Lodge",address:"Heaton Moor Road",area:"Heaton Moor",postcode:"SK4",price:260000,qualifier:"Asking price",bedrooms:2,bathrooms:1,type:"Apartment",status:"For sale",image:photos[3],collection:["Village life","First-time favourites"],description:"An immaculate ground-floor apartment with two double bedrooms and parking, close to Heaton Moor's restaurants and Heaton Chapel station.",sourceUrl:"https://www.gascoignehalman.co.uk/property-details/1048236/greater-manchester/stockport/thorn-bank-lodge"},
{slug:"cranbourne-court",title:"Cranbourne Court",address:"Cranbourne Road",area:"Heaton Moor",postcode:"SK4",price:175000,qualifier:"Asking price",bedrooms:1,bathrooms:1,type:"Apartment",status:"For sale",image:photos[5],collection:["Village life","First-time favourites"],description:"A well-presented first-floor apartment with parking, close to the amenities, restaurants and transport links of Heaton Moor.",sourceUrl:"https://www.gascoignehalman.co.uk/property-details/1036777/greater-manchester/stockport/cranbourne-court-cranbourne-road"}
];
export const collectionDescriptions:Record<string,string>={"Village life":"Independent shops, good coffee and a proper neighbourhood rhythm.","Metrolink movers":"Homes that make the commute into Manchester feel refreshingly simple.","Family space":"Gardens, flexible rooms and space for everyday life to spread out.","First-time favourites":"Approachable Greater Manchester homes with plenty to grow into."};
export const formatPrice=(price:number)=>new Intl.NumberFormat("en-GB",{style:"currency",currency:"GBP",maximumFractionDigits:0}).format(price);
