"use client";
import "./portal.css";
import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { CalendarDays, ChevronRight, CircleUserRound, Clock3, Home, LayoutDashboard, LogOut, MessageCircle, PoundSterling, Send, Settings2 } from "lucide-react";
import { buyingPositions, depositStatuses, mortgageStatuses } from "@/lib/viewing-profile-options";

type User={id:string;name:string;email:string;role:string;phone:string;buying_position:string;deposit_status:string;mortgage_status:string};
type Application={id:string;application_reference:string;property_slug:string;viewing_slot:string;status:string;created_at:string;applicant_name?:string;buying_position?:string};
type Message={id:string;application_id:string;body:string;created_at:string;sender_user_id:string;sender_name:string};
type Offer={id:string;property_slug:string;amount:number;status:string;created_at:string;buyer_name:string};
type PortalData={user:User;buyerApplications:Application[];sellerRequests:Application[];messages:Message[];offers:Offer[];properties:{property_slug:string;title:string}[]};
const labels:Record<string,string>={"oakfield-house-wilmslow":"Oakfield House","fairfax-didsbury":"The Fairfax","fog-lane-didsbury":"Fog Lane"};

export default function PortalPage(){const [data,setData]=useState<PortalData|null>(null);const [tab,setTab]=useState("overview");const [selected,setSelected]=useState<string>("");const [message,setMessage]=useState("");const [notice,setNotice]=useState("");const router=useRouter();
  async function load(){const response=await fetch("/api/portal",{cache:"no-store"});if(response.status===401){router.replace("/account");return;}const body=await response.json();setData(body);const first=body.sellerRequests?.[0]?.id||body.buyerApplications?.[0]?.id;if(first&&!selected)setSelected(first);}
  useEffect(()=>{load()},[]);
  const conversations=useMemo(()=>data?[...data.sellerRequests,...data.buyerApplications].filter((a,i,list)=>list.findIndex(x=>x.id===a.id)===i):[],[data]);
  async function send(event:FormEvent){event.preventDefault();if(!selected||!message.trim())return;await fetch("/api/messages",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({applicationId:selected,body:message})});setMessage("");await load();}
  async function saveProfile(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);const response=await fetch("/api/account",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:form.get("name"),phone:form.get("phone"),buyingPosition:form.get("buyingPosition"),depositStatus:form.get("depositStatus"),mortgageStatus:form.get("mortgageStatus")})});setNotice(response.ok?"Profile saved":"Could not save profile");await load();}
  async function logout(){await fetch("/api/account",{method:"DELETE"});router.replace("/account");router.refresh();}
  if(!data)return <main className="portal-loading"><span>L</span><p>Opening your workspace…</p></main>;
  const appointments=data.user.role==="seller"?data.sellerRequests:data.user.role==="both"?[...data.sellerRequests,...data.buyerApplications]:data.buyerApplications;
  return <main className="portal-page"><aside className="portal-nav"><Link href="/" className="portal-brand"><span>L</span><b>listwise.</b></Link><nav>{[["overview",LayoutDashboard,"Overview"],["diary",CalendarDays,"Diary"],["messages",MessageCircle,"Messages"],["offers",PoundSterling,"Offers"],["profile",Settings2,"My profile"]].map(([id,Icon,label])=><button key={String(id)} className={tab===id?"active":""} onClick={()=>setTab(String(id))}>{<Icon/>}<span>{String(label)}</span></button>)}</nav><div className="portal-user"><CircleUserRound/><span><b>{data.user.name}</b><small>{data.user.email}</small></span><button onClick={logout} aria-label="Sign out"><LogOut/></button></div></aside><section className="portal-main"><header><div><p className="eyebrow">Property workspace</p><h1>{tab==="overview"?`Hello, ${data.user.name.split(" ")[0]}`:tab[0].toUpperCase()+tab.slice(1)}</h1></div><Link href="/homes">Browse homes <ChevronRight/></Link></header>
  {tab==="overview"&&<><div className="portal-metrics"><article><CalendarDays/><span><small>Upcoming viewings</small><b>{appointments.length}</b></span></article><article><MessageCircle/><span><small>Conversations</small><b>{conversations.length}</b></span></article><article><PoundSterling/><span><small>Active offers</small><b>{data.offers.filter(o=>o.status==="submitted").length}</b></span></article></div><div className="portal-columns"><section><div className="portal-section-title"><h2>Next in your diary</h2><button onClick={()=>setTab("diary")}>View diary</button></div><AppointmentList items={appointments}/></section><section><div className="portal-section-title"><h2>Recent conversations</h2><button onClick={()=>setTab("messages")}>Open messages</button></div>{conversations.slice(0,3).map(a=><button className="conversation-row" key={a.id} onClick={()=>{setSelected(a.id);setTab("messages")}}><span>{(a.applicant_name||data.user.name).slice(0,2).toUpperCase()}</span><div><b>{a.applicant_name||labels[a.property_slug]||"Viewing conversation"}</b><small>{labels[a.property_slug]||a.property_slug} · {a.application_reference}</small></div><ChevronRight/></button>)}{!conversations.length&&<Empty text="Messages will appear alongside each viewing request."/>}</section></div></>}
  {tab==="diary"&&<section className="portal-surface"><div className="portal-section-title"><div><h2>Viewing diary</h2><p>Requests and confirmed appointments in one place.</p></div></div><AppointmentList items={appointments}/></section>}
  {tab==="messages"&&<section className="messages-layout"><aside>{conversations.map(a=><button className={selected===a.id?"active":""} key={a.id} onClick={()=>setSelected(a.id)}><span>{(a.applicant_name||"OH").slice(0,2).toUpperCase()}</span><div><b>{a.applicant_name||labels[a.property_slug]||"Viewing"}</b><small>{a.application_reference}</small></div></button>)}{!conversations.length&&<Empty text="Submit or receive a viewing request to start chatting."/>}</aside><div className="chat-panel"><header><b>{conversations.find(a=>a.id===selected)?.applicant_name||labels[conversations.find(a=>a.id===selected)?.property_slug||""]||"Viewing messages"}</b><small>Messages stay attached to this booking.</small></header><div className="chat-log">{data.messages.filter(m=>m.application_id===selected).map(m=><div className={m.sender_user_id===data.user.id?"mine":""} key={m.id}><small>{m.sender_name}</small><p>{m.body}</p></div>)}{selected&&!data.messages.some(m=>m.application_id===selected)&&<Empty text="No messages yet. Say hello or ask about access and timing."/>}</div>{selected&&<form onSubmit={send}><input value={message} onChange={e=>setMessage(e.target.value)} placeholder="Write a message…"/><button aria-label="Send message"><Send/></button></form>}</div></section>}
  {tab==="offers"&&<section className="portal-surface"><div className="portal-section-title"><div><h2>Offers</h2><p>Track submitted, accepted and declined offers.</p></div></div>{data.offers.map(o=><article className="offer-row" key={o.id}><PoundSterling/><div><b>{labels[o.property_slug]||o.property_slug}</b><small>{o.buyer_name} · {new Date(o.created_at).toLocaleDateString("en-GB")}</small></div><strong>{new Intl.NumberFormat("en-GB",{style:"currency",currency:"GBP",maximumFractionDigits:0}).format(o.amount)}</strong><span>{o.status}</span></article>)}{!data.offers.length&&<Empty text="Offers will appear here with a clear status and audit trail."/>}</section>}
  {tab==="profile"&&<section className="portal-surface profile-surface"><div className="portal-section-title"><div><h2>Reusable viewing profile</h2><p>We’ll prefill these details the next time you apply to view a home.</p></div></div><form onSubmit={saveProfile}><label>Full name<input name="name" defaultValue={data.user.name}/></label><label>Phone<input name="phone" defaultValue={data.user.phone}/></label><label>Buying position<select name="buyingPosition" defaultValue={data.user.buying_position}><option value="">Select your position</option>{buyingPositions.map(option=><option key={option}>{option}</option>)}</select></label><label>Deposit status<select name="depositStatus" defaultValue={data.user.deposit_status}><option value="">Select deposit status</option>{depositStatuses.map(option=><option key={option}>{option}</option>)}</select></label><label>Mortgage status<select name="mortgageStatus" defaultValue={data.user.mortgage_status}><option value="">Select mortgage status</option>{mortgageStatuses.map(option=><option key={option}>{option}</option>)}</select></label><button>Save profile</button>{notice&&<p>{notice}</p>}</form></section>}
  </section></main>}
function AppointmentList({items}:{items:Application[]}){return <div className="appointment-list">{items.map(item=><article key={item.id}><div className="date-tile"><CalendarDays/><span>{item.viewing_slot.split(" · ")[0]}</span></div><div><b>{item.applicant_name||labels[item.property_slug]||item.property_slug}</b><small><Clock3/>{item.viewing_slot} · {item.application_reference}</small></div><span className="booking-status">{item.status.replaceAll("_"," ")}</span></article>)}{!items.length&&<Empty text="No viewing requests yet. Your diary is ready when they arrive."/>}</div>}
function Empty({text}:{text:string}){return <div className="portal-empty"><Home/><p>{text}</p></div>}
